"""Assign a usage-based category to a prompt."""

from __future__ import annotations

from crawler.config import CATEGORIES

_KEYWORDS: dict[str, tuple[str, ...]] = {
    "cinematic": (
        "cinematic",
        "film",
        "short film",
        "scene 1",
        "scene 2",
        "narrative",
        "storytelling",
        "drama",
        "dialogue",
        "act 1",
        "act 2",
        "noir",
        "thriller",
        "horror",
        "sci-fi",
        "fantasy",
        "documentary",
        "slow zoom",
        "dolly",
        "crane shot",
        "tracking shot",
        "steadicam",
        "film grain",
        "color grade",
        "35mm",
        "anamorphic",
        "unreal engine",
        "ray tracing",
    ),
    "commercial": (
        "commercial",
        "advertisement",
        "ad ",
        "brand",
        "product shot",
        "packshot",
        "marketing",
        "promo ",
        "promotion",
        "luxury",
        "fashion",
        "beauty",
        "food ",
        "beverage",
        "automotive",
        "real estate",
        "showcase",
        "demo",
    ),
    "music-video": (
        "music video",
        "lip sync",
        "lip-sync",
        "beat drop",
        "rhythm",
        "concert",
        "singer",
        "singing",
        "performer",
        "choreograph",
        "stage",
        "neon lights",
        "strobe",
        "dance performance",
        "dance routine",
        "dj ",
        "rap ",
        "hip hop",
    ),
    "social-content": (
        "ugc",
        "tiktok",
        "reels",
        "instagram",
        "social media",
        "selfie",
        "vlog",
        "vertical",
        "9:16",
        "trending",
        "viral",
        "influencer",
        "creator",
        "pov ",
        "point of view",
        "unboxing",
        "haul",
        "get ready",
        "day in",
        "mobile phone footage",
        "smartphone",
    ),
    "character": (
        "portrait",
        "close-up face",
        "expression",
        "costume",
        "outfit",
        "warrior",
        "cyborg",
        "robot",
        "superhero",
        "anime character",
        "walk cycle",
        "walk and talk",
        "character-led",
        "character driven",
        "model pose",
    ),
    "nature-scenic": (
        "landscape",
        "nature",
        "mountain",
        "forest",
        "ocean",
        "sunset",
        "sunrise",
        "aerial drone",
        "drone shot",
        "wildlife",
        "beach",
        "waterfall",
        "timelapse",
        "time-lapse",
        "desert",
        "underwater",
        "cherry blossom",
        "golden hour",
        "blue hour",
        "aurora",
        "starscape",
    ),
    "vfx": (
        "vfx",
        "visual effect",
        "explosion",
        "particle",
        "magic",
        "fire ",
        "lightning",
        "smoke ",
        "portal",
        "transform",
        "morph",
        "disintegrate",
        "shatter",
        "dissolve",
        "glitch",
        "hologram",
        "tentacle",
        "energy",
        "power",
    ),
}


def categorize(text: str) -> str:
    lower = text.lower()
    best = "other"
    best_hits = 0
    for cat in CATEGORIES:
        if cat == "other":
            continue
        hits = sum(1 for kw in _KEYWORDS.get(cat, ()) if kw in lower)
        if hits > best_hits:
            best = cat
            best_hits = hits
    return best
