"""Known AI / generative video tool handles and brand names for promo stripping.

Handles are matched *without* the leading @. Extend via data/trim_rules.json commercial_handles.
"""

from __future__ import annotations

# X/Twitter-style handles (lowercase). Include common variants and typos seen in the wild.
AI_VIDEO_TOOL_HANDLES: frozenset[str] = frozenset(
    {
        # Seedance / ByteDance ecosystem
        "seedance",
        "seedanceai",
        "seedance_ai",
        "bytedance",
        "bytedanceai",
        "doubao",
        "capcut",
        "capcutapp",
        "dreamina",
        "dreamina_ai",
        "jimeng",
        "jimeng_ai",
        # Major video / multimodal
        "openai",
        "openai_",
        "sora",
        "googledeepmind",
        "googleai",
        "gemini",
        "veo",
        "metaai",
        "meta",
        "lumalabsai",
        "lumaai",
        "luma_ai",
        "luma",
        "runwayml",
        "runwayapp",
        "runway",
        "runway_gen4",
        "klingai",
        "kling_ai",
        "kling_labs",
        "minimax",
        "minimax_ai",
        "hailuoai",
        "hailuoai_official",
        "hailuo_ai",
        "viduofficial",
        "vidu_ai",
        "vidu",
        "pixverse",
        "pixverseai",
        "pixverse_ai",
        "pixaborai",
        "pika_labs",
        "pikapikapika",
        "paborika_app",
        "genmoai",
        "genmo_ai",
        "genmo",
        "morphstudioai",
        "morph_ai",
        "domoai",
        "domo_ai",
        "leonardoai",
        "leonardo_ai",
        "leonardo",
        "midjourney",
        "midaborjourney",
        "stabilityai",
        "staaborility_ai",
        "ideogram_ai",
        "ideaborogram",
        "ideogram",
        "fluxai",
        "flux_ai",
        "blackforestlabs",
        "bfl_ml",
        # Editing / ads / avatars
        "adobe",
        "adobefirefly",
        "firefly",
        "canva",
        "invideo_ai",
        "invaborideoai",
        "invideo",
        "synthesia_io",
        "synthaboresia",
        "synthesia",
        "heygenofficial",
        "heygen_official",
        "heygen",
        "d_id_official",
        "d_id_",
        "did_official",
        "elevenlabs",
        "elevenaborlabs",
        "suno_ai_",
        "sunomusic",
        "suno",
        "udiomusic",
        "udio",
        "topazorlabs",
        "topaborazlabs",
        "topazlabs",
        "magnific_ai",
        "magnaborific",
        "magnific",
        "polloai",
        "pollo_ai",
        "higgsfield",
        "higgsfield_ai",
        "lart_ai",
        "lartai",
        "haiper_ai",
        "haiperofficial",
        "haiper",
        "noisee_ai",
        "noiseeai",
        "noisee",
        # Distribution / wrappers / regional
        "topviewaihq",
        "topview",
        "topviewai",
        "youartstudio",
        "youart",
        "nsketchai",
        "nsketch",
        "deepvid",
        "deepvidai",
        "freepik",
        "freepikaistudio",
        "freepik_ai",
        "replicate",
        "replicatehq",
        "huggingface",
        "civitai",
        "tensorart",
        "seaart_ai",
        "seaart",
        "kaborai",
        "kaboraai",
        "martiniai",
        "martiniart_",
        "martiniai_",
        "martini_art",
        "kaiber",
        "kaiberai",
        "kaiber_ai",
        "opusclip",
        "opus_clip",
        "creatorkit",
        "opclip",
        "descript",
        "jasperai",
        "jasper",
        "grok",
        "grokai",
        "grok_imagine",
        "xai",
        "anthropicai",
        "anthropic",
        "claudeai",
        "claude",
        "openrouter",
        "pika_labs",
        "alibaba_aigc",
        "tongyi",
        "wan_ai",
        "wanx",
        "lightricks",
        "ltxstudio",
        "ltx_video",
        "viggleai",
        "viggle",
        "zmo_ai",
        "zmo",
        "cutoutpro",
        "kreadoai",
        "invideoio",
        "synthesia_io",
        "lensgo",
        "lenstudio",
        "pictory",
        "pictoryai",
        "synthesys",
        "flexclip",
        "animaker",
        "rawshorts",
        "steveai",
        "elai_io",
        "colossyan",
        "hourone",
        "deepbrainai",
        "synthesia",
        "kapwing",
        "clipchamp",
        "filmora",
        "wondershare",
        "movavi",
        "veed",
        "veedstudio",
        "lumen5",
        "offeo",
        "renderforest",
        "biteable",
        "powtoon",
        "vyond",
    }
)

# Multi-word or non-handle brand phrases (lowercase) for word-boundary matching in sentences.
AI_VIDEO_BRAND_PHRASES: frozenset[str] = frozenset(
    {
        "luma labs",
        "luma dream machine",
        "runway ml",
        "runway gen",
        "google veo",
        "openai sora",
        "adobe firefly",
        "stable diffusion",
        "stability ai",
        "midjourney v",
        "pika labs",
        "kling ai",
        "hailuo ai",
        "minimax video",
        "byteplus",
        "capcut pro",
        "dreamina ai",
        "seedance 2",
        "seedance 2.0",
        "sd 2.0",
        "topaz labs",
        "eleven labs",
        "d-id",
        "hey gen",
        "suno ai",
        "google ai",
        "meta ai",
        "x ai",
        "grok imagine",
        "replicate.com",
        "hugging face",
        "leonardo ai",
        "domo ai",
        "morph studio",
        "haiper ai",
        "pollo ai",
        "lart ai",
        "higgsfield ai",
        "topview ai",
        "youart studio",
        "opus clip",
        "freepik ai",
        "seaart ai",
        "tensor art",
        "civit ai",
        "nvidia canvas",
        "runway research",
    }
)

# Hashtag stems (no #): strip sentences/lines that are mostly promo tags.
PROMO_HASHTAG_STEMS: frozenset[str] = frozenset(
    {
        "seedance",
        "seedance2",
        "seedance20",
        "sd2",
        "sd20",
        "bytedance",
        "capcut",
        "dreamina",
        "dreaminacpp",
        "dreaminaai",
        "luma",
        "runway",
        "kling",
        "pika",
        "pixverse",
        "midjourney",
        "mj",
        "aiart",
        "aivideo",
        "aitools",
        "generativeai",
        "texttovideo",
        "ttv",
        "promptshare",
        "ad",
        "ai",
        "ml",
        "mv",
        "sponsored",
        "giveaway",
        "linkinbio",
        "followforfollow",
        "fyp",
        "grok",
        "grokimagine",
        "sora",
        "veo",
        "firefly",
        "heygen",
        "synthesia",
        "invideo",
    }
)
